redis.host=${REDIS_HOST:localhost}
redis.port=${REDIS_PORT:6379}
redis.queue=${REDIS_QUEUE:scan-jobs}
redis.dlq=${REDIS_DLQ:scan-dlq}
worker.threads=${WORKER_THREADS:4}
worker.blpop.timeout=${WORKER_BLPOP_TIMEOUT:5}
db.url=${DB_URL:localhost}
db.username=${DB_USERNAME:postgres}
db.password=${DB_PASSWORD:postgres}
groq.api.key=${GROQ_API_KEY:123456723456789}
anthropic.api.key=${ANTHROPIC_API_KEY:poiuytrewertyuio}
grok.api.key=${GROK_API_KEY:poiuytrertyui}
gemini.api.key=${GEMINI_API_KEY:jhgfdsdfghj}