using Domain.Enums;

namespace Domain.Entities;

public class Waitlist : EntityBase
{
    // Every user starts their referral ranking at this fixed base, independent of join order.
    public const long InitialReferralPosition = 40;

    public string Email { get; private set; } = default!;
    public string? CompanyName { get; private set; }
    public string? Comments { get; private set; }
    public WaitlistStatus Status { get; private set; } = WaitlistStatus.Pending;
    // Monotonic confirmation sequence, assigned only once the email is confirmed (null before
    // then and after cancellation). Used as the stable ordering key; the queue number shown to
    // users is derived as the live rank among active entries, so cancellations shift everyone up.
    public long? Position { get; private set; }
    public bool EmailConfirmed { get; private set; }
    public string? EmailConfirmationToken { get; private set; }
    public DateTime? EmailConfirmedAt { get; private set; }
    public string? InvitationToken { get; private set; }
    public Guid? PromotedUserId { get; private set; }
    public DateTime? PromotedAt { get; private set; }
    public string? Notes { get; private set; }
    // Assigned only on email confirmation (null before then).
    public string? ReferralCode { get; private set; }
    public Guid? ReferredByWaitlistId { get; private set; }
    public int ReferralCount { get; private set; }
    // The allowlisted frontend origin (scheme://host[:port]) the entry joined from, captured at join
    // so environment-aware links (e.g. the referral link built at confirmation time, when the request
    // may not carry an Origin header) can route back to the same frontend. Null when the join came
    // from an unknown/non-allowlisted origin. Never holds an un-allowlisted value — see WaitlistLinks.
    public string? JoinOrigin { get; private set; }
    // Referral ranking, independent of the join-order Position. Starts at a fixed base
    // (InitialReferralPosition) for every user and decreases by 1 per referral (floored at 1).
    // Lower = more referrals = higher reward priority.
    public long ReferralPosition { get; private set; }
    public DateTime? LastReferralAt { get; private set; }

    private Waitlist() { }

    public static Waitlist Create(
        string email,
        string? companyName = null,
        string? comments = null,
        Guid? referredByWaitlistId = null)
        => new()
        {
            Email = email,
            CompanyName = companyName,
            Comments = comments,
            Status = WaitlistStatus.Pending,
            EmailConfirmed = false,
            // Position and ReferralCode are intentionally left unset until email confirmation.
            ReferredByWaitlistId = referredByWaitlistId,
            ReferralCount = 0,
            ReferralPosition = InitialReferralPosition,
        };

    public void GenerateEmailConfirmationToken(string token)
    {
        EmailConfirmationToken = token;
        Touch();
    }

    /// <summary>
    /// Confirms the email and claims the queue slot: assigns the monotonic <paramref name="position"/>
    /// sequence and the user's <paramref name="referralCode"/>. Both are provided by the caller,
    /// which has the repository context needed to allocate a unique sequence and code.
    /// </summary>
    public void ConfirmEmail(long position, string referralCode)
    {
        if (EmailConfirmed)
            return;

        EmailConfirmed = true;
        Status = WaitlistStatus.EmailConfirmed;
        EmailConfirmedAt = DateTime.UtcNow;
        EmailConfirmationToken = null;
        Position = position;
        ReferralCode = referralCode;
        Touch();
    }

    public bool ValidateEmailConfirmationToken(string token)
    {
        return !string.IsNullOrEmpty(EmailConfirmationToken) && EmailConfirmationToken == token && !EmailConfirmed;
    }

    public void GenerateInvitationToken(string token)
    {
        InvitationToken = token;
        Touch();
    }

    public void MarkPromoted(Guid userId)
    {
        Status = WaitlistStatus.Promoted;
        PromotedUserId = userId;
        PromotedAt = DateTime.UtcNow;
        InvitationToken = null;
        Touch();
    }

    public void MarkCancelled()
    {
        Status = WaitlistStatus.Cancelled;
        // Free the queue slot so it no longer counts toward anyone's live position.
        Position = null;
        Touch();
    }

    /// <summary>
    /// Reactivates a previously cancelled entry so the email can rejoin the waitlist as a fresh
    /// pending signup: clears the confirmed state, queue slot, referral code and referral stats,
    /// and (re)links the referrer. A new confirmation token must be generated by the caller.
    /// </summary>
    public void Reactivate(Guid? referredByWaitlistId)
    {
        Status = WaitlistStatus.Pending;
        EmailConfirmed = false;
        EmailConfirmedAt = null;
        Position = null;
        ReferralCode = null;
        ReferralCount = 0;
        ReferralPosition = InitialReferralPosition;
        LastReferralAt = null;
        ReferredByWaitlistId = referredByWaitlistId;
        Touch();
    }

    public void UpdateNotes(string? notes)
    {
        Notes = notes;
        Touch();
    }

    public void UpdateCompanyName(string? companyName)
    {
        CompanyName = companyName;
        Touch();
    }

    public void UpdateComments(string? comments)
    {
        Comments = comments;
        Touch();
    }

    /// <summary>
    /// Records the allowlisted frontend origin this entry joined from. The caller is responsible for
    /// only passing an origin that has been validated against the allowlist (null clears it).
    /// </summary>
    public void SetJoinOrigin(string? origin)
    {
        JoinOrigin = origin;
        Touch();
    }

    public void MarkReferredBy(Guid waitlistId)
    {
        ReferredByWaitlistId = waitlistId;
        Touch();
    }
}
